openapi: 3.0.3
info:
  title: Productos API
  version: 1.0.0
  description: API for managing products with RabbitMQ messaging and JWT authentication.
servers:
  - url: http://localhost:5000

paths:
  /productos:
    get:
      summary: Obtener todos los productos
      description: Devuelve la lista de todos los productos registrados.
      security:
        - BearerAuth: []
      responses:
        '200':
          description: Lista de productos obtenida exitosamente.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                      example: 1
                    nombre:
                      type: string
                      example: "Producto A"
                    descripcion:
                      type: string
                      example: "Descripción del producto A"
        '401':
          description: No autorizado. Token inválido o no proporcionado.

    post:
      summary: Crear un nuevo producto
      description: Crea un nuevo producto y publica un mensaje en RabbitMQ.
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Producto B"
                descripcion:
                  type: string
                  example: "Descripción del producto B"
              required:
                - nombre
                - descripcion
      responses:
        '201':
          description: Producto creado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 2
                  mensaje:
                    type: string
                    example: "Producto creado exitosamente"
        '400':
          description: Datos de producto inválidos o incompletos.
        '500':
          description: Error al publicar el mensaje o crear el producto.
        '401':
          description: No autorizado. Token inválido o no proporcionado.

  /productos/{id}:
    get:
      summary: Obtener producto por ID
      description: Devuelve los detalles de un producto específico por su ID.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      responses:
        '200':
          description: Producto encontrado.
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                    example: 1
                  nombre:
                    type: string
                    example: "Producto A"
                  descripcion:
                    type: string
                    example: "Descripción del producto A"
        '404':
          description: Producto no encontrado.
        '401':
          description: No autorizado. Token inválido o no proporcionado.

    put:
      summary: Actualizar un producto por ID
      description: Actualiza los detalles de un producto específico.
      security:
        - BearerAuth: []
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
            example: 1
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                  example: "Producto A Actualizado"
                descripcion:
                  type: string
                  example: "Descripción actualizada del producto A"
              required:
                - nombre
                - descripcion
      responses:
        '200':
          description: Producto actualizado exitosamente.
          content:
            application/json:
              schema:
                type: object
                properties:
                  mensaje:
                    type: string
                    example: "Producto actualizado exitosamente"
        '404':
          description: Producto no encontrado.
        '401':
          description: No autorizado. Token inválido o no proporcionado.

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
