openapi: 3.0.0
info:
  title: Servicio de Productos
  version: 1.0.0
  description: API para gestionar el inventario de productos

paths:
  /productos:
    get:
      summary: Obtener lista de productos
      responses:
        '200':
          description: Lista de productos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    nombre:
                      type: string
                    cantidad:
                      type: integer
                    ubicacion:
                      type: string
        '500':
          description: Error de servidor

    post:
      summary: Crear un nuevo producto
      requestBody:
        description: Datos del producto
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nombre
                - cantidad
                - ubicacion
              properties:
                nombre:
                  type: string
                cantidad:
                  type: integer
                ubicacion:
                  type: string
      responses:
        '201':
          description: Producto creado exitosamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  mensaje:
                    type: string
        '400':
          description: Datos de producto inválidos
        '500':
          description: Error de comunicación al crear el producto

  /productos/{id}:
    get:
      summary: Obtener un producto por ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto
      responses:
        '200':
          description: Detalles del producto
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  nombre:
                    type: string
                  cantidad:
                    type: integer
                  ubicacion:
                    type: string
        '404':
          description: Producto no encontrado
        '500':
          description: Error de servidor

    put:
      summary: Actualizar un producto por ID
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: ID del producto a actualizar
      requestBody:
        description: Datos actualizados del producto
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                nombre:
                  type: string
                cantidad:
                  type: integer
                ubicacion:
                  type: string
      responses:
        '200':
          description: Producto actualizado exitosamente
        '404':
          description: Producto no encontrado
        '500':
          description: Error de comunicación al actualizar el producto
